# Generated by Django 2.0 on 2017-12-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAnews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=36, null=True)),
                ('pubtime', models.CharField(max_length=36, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
